export enum Role {
   PASIEN = "PASIEN",
   DOKTER = "DOKTER",
   ADMINISTRASI = "ADMINISTRASI",
   PENGELOLA_OBAT = "PENGELOLA_OBAT",
}

export type RoleType = "PASIEN" | "DOKTER" | "ADMINISTRASI" | "PENGELOLA_OBAT";
